### ISSUE TITLE
Start button on dashboard doesn't work

### ISSUE THREAD

**Issue by blazv** [openbaton/NFVO#10]
In the VNF Package menu when I click `Start` button it returns with the following error:
`Uncaught Error: This file can't be queued because it has already been processed or was rejected.`

![vnfp](https://cloud.githubusercontent.com/assets/16189252/11954007/1ef94c16-a8a5-11e5-8cfe-8a72e46e480d.JPG)

`Send All` button works well though .

Regards, Blazv

**Comment by gc4rella** [comment]
Thx for reporting, Nico (responsible for the dashboard) will look into it.

**Comment by nicob22** [comment]
Thanks for the info, the `Start` and `Delete` buttons were in conflict with `Send All` button, from now the packages are uploaded with `Send All` button.
Cheers, Nico
