### ISSUE TITLE
In case requires is set in a VNFD, the NFVO should not wait when source VNF is not present in NSD

### ISSUE THREAD

**Issue by gc4rella** [openbaton/NFVO#114]
In case requires is set in a VNFD, the NFVO should not wait when source VNF is not present in NSD. 

Example of VNFD:  

```json
...
"requires":{
	"server":{
		"parameters":["netname_floatingIp"]
	}
}
...
```

however, NSD does not contain any server VNF. Therefore the NFVO should not wait during CONFIGURE lifecycle.

**Comment by lorenzotomasini** [comment]
If the VNF that provides the parameter is not in the NSD you should get an error while uploading the NS. @ThomasBri is this the case?

**Comment by ThomasBri** [comment]
Yes, I checked it and I was not able to upload an NSD containing a requires field which referenced a non existing VNFD's name.

**Comment by gc4rella** [comment]
can be closed?

**Comment by lorenzotomasini** [comment]
yes
