### ISSUE TITLE
request example of vnfd and nsd

### ISSUE THREAD

**Issue by chart2023** [openbaton/NFVO#12]
Can you give me the example of vnfd for iperf-server and iperf-client script and example of NSD?
I follow the instruction in the openbaton website, It can launch instance but It show 'error' in log file.

**Comment by marcellom** [comment]
Hello, 
first of all, sorry for the late response.

This is a NSD for the iperf-server scenario
[NetworkServiceDescriptor-iperf-server-example.txt](https://github.com/openbaton/NFVO/files/89059/NetworkServiceDescriptor-iperf-server-example.txt)

Note1: remember to change the extension of the file from "txt" to "json".
Note 2: put a valid link in the field "scriptsLink" in the json file. It should be a git public link, where the ems will download all the scripts.

The scripts used in the NSD are: 
iperf-server:
- install.sh [install.txt](https://github.com/openbaton/NFVO/files/89103/install.txt)
- start-srv.sh [start-srv.txt](https://github.com/openbaton/NFVO/files/89104/start-srv.txt)

iperf-client:
- install.sh [install.txt](https://github.com/openbaton/NFVO/files/89105/install.txt)
- server_start-clt.sh [server_start-clt.txt](https://github.com/openbaton/NFVO/files/89109/server_start-clt.txt)

Note 3: remember to change the extension of all the scripts from "txt" to "sh". (Git doesn't allow to update files with some extensions)

Cheers,
Marcello

PS. I'm going to close this issue. Please for this informations use the mail users@openbaton.org

**Comment by chart2023** [comment]
thank you
