### ISSUE TITLE
downloading NSD/VNFD from marketplace should not be allowed while using unsupported VIM plugins

### ISSUE THREAD

**Issue by gc4rella** [openbaton/NFVO#121]
Clicking download NSD from marketplace while having a PoP registered using a non openstack plugin (for instance test), generates an error displayed on the dashboard as: 

> An error occured and could not be handled properly, please, report to us and we will fix it as soon as possible

on the NFVO logs: 

`2017-03-28 11:18:52.377 ERROR 14 --- [http-nio-8080-exec-9] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.UnsupportedOperationException] with root cause

java.lang.UnsupportedOperationException: null
	at org.openbaton.vim_impl.vim.TestVIM.add(TestVIM.java:117)
	at org.openbaton.nfvo.core.api.VNFPackageManagement.handleImage(VNFPackageManagement.java:524)
	at org.openbaton.nfvo.core.api.VNFPackageManagement.onboard(VNFPackageManagement.java:179)`

Therefore, download from marketplace should be allowed only for VIM supporting this functionality.

**Comment by lorenzotomasini** [comment]
Problem here is that the VNFPackage metadata is not containing the "vim_types". so the NFVO cannot check if it is possible to add an image.

@gc4rella Should i put this field mandatory?

**Comment by lorenzotomasini** [comment]
![screen shot 2017-04-06 at 12 07 54](https://cloud.githubusercontent.com/assets/3480153/24748991/c66ac4c2-1ac1-11e7-8040-88366aedebae.png)
