### ISSUE TITLE
Install plugin functionality 

### ISSUE THREAD

**Issue by gc4rella** [openbaton/NFVO#122]
The install plugin functionality has some weird behaviour..I tried stopping a plugin `kill plugin-pid` and using the install button from the dashboard. 

First, a new jar file of the plugin is downloaded although the same plugin is already present in vim-drivers. Probably this is due to the fact that in marketplace vim drivers do not use the same name convention as in the debian packages (for instance..TestPlugin). 

Second, the download function creates a new folder (install-plugin) inside the /usr/lib/openbaton/plugins/vim-drivers/ folder. What's the main reason?

**Comment by lorenzotomasini** [comment]
@radoslavvlaskovski @ogozman any news here? or should i have i look?

**Comment by radoslavvlaskovski** [comment]
https://github.com/openbaton/NFVO/tree/issue-%23122 
fixes are here, currently double checking everything again before creating a pull request.

**Comment by lorenzotomasini** [comment]
```java

@Value("${nfvo.plugin.installation-dir:./plugins}")
private String pluginDir;

String path = pluginDir + "/install-plugin/" + name + ".jar";
```

so the downloaded location is the plugin dir in order to restart it if the nfvo is restarted too.
we don't have a good mechanism to identify to which jar the running plugin points to. That is why, even if you kill the plugin, the install plugin from the gui will redownload it anyway and restart it.
