### ISSUE TITLE
create event allows creation of events with non-existing IDs

### ISSUE THREAD

**Issue by gc4rella** [openbaton/NFVO#124]
Create event allows the creation of events containing also non-existing NSR IDs of VNF IDs. example: 
`{
    "id": "ae9eda3c-1f6a-49fb-a321-03f569ec0e0b",
    "version": 0,
    "name": "event_name",
    "projectId": "5dae3777-8072-4058-b8ed-baf3afcad06e",
    "networkServiceId": "123123",
    "virtualNetworkFunctionId": "",
    "type": "REST",
    "endpoint": "localhost:8080/events",
    "event": "INSTANTIATE_FINISH"
}`

in addition, the event can't support the NSR IDs AND VNF IDs (it is a XOR!). Furthermore, would be good to describe what are those IDs (VNFD or VNFR ID?!)

**Comment by zohaibhassan122** [comment]
I can put the descriptions of VNFD and VNFR IDs in a tool tip with input box and We will mention that its a XOR action you can select one of them or none. If you guys can give me proper description for VNFD and VNFR ID that would be great.

Regarding event creation, It should be handled by back-end.

Thanks for your support.

**Comment by zohaibhassan122** [comment]
Resolved:
Added Description for NSR and VNFR in tool-tip.
https://github.com/openbaton/dashboard/commit/5c14c889f303b06e0a8a5d62a33456996a28b40a
