### ISSUE TITLE
Assign Fixed IP Address to VNF

### ISSUE THREAD

**Issue by rensubi** [openbaton/NFVO#126]
Assign a fixed ip to VNF if it is available in the range of the subnet

To assign a fixed ip to VNF,  add fixedIp name value pair to vnfd.json.

Example:

               "vnfc":[
                  {
                     "connection_point":[
                        {
                           "fixedIp":"192.168.0.19",
                           "virtual_link_reference":"mgmt"
                        }
                      ]
                  }
               ],

**Comment by mpauls** [comment]
two problems I see with this approach: 

What happens if the the networks are created on demand by the NFVO with a random CIDR. How can we handle this if fixedIp and network CIDR doesn't match? 

Another problem is how to deploy several instances of a given NSD with fixedIps?

**Comment by rensubi** [comment]
One important thing to note is that if the fixed ip field is not included in the config file the code will continue to function exactly as before.  This is an optional field and really only applies to certain use cases.  The expected use case of the fixed IP code is that the network will already exist and it is desired that a box continue to use the same IP address.  This would be important for things like limiting having to open up firewalls for new IP addresses, etc.
 
For you first question:   If the fixedIp and network CIDR don't match, the expected result is that no VM will be created. 
 
Currently, if the fixedIp  doesn't match CIDR, such as 192.160.0.19 if CIDR is 192.168.0.0/24, an exception is thrown, but an inaccessible vm with status ERROR is created.
 
We tested the case with OpenStack CLI, the same result returned.
 
# nova boot fixedIp_case41 --flavor vzw.m1.small --image internet.ubuntu.x86_64.v16.04 --security-group default --key-name  subin_reston  \
        --nic net-name=mgmt,v4-fixed-ip=192.160.0.21
  
We are going to open a bug report to openstack since we believe openstack doesn’t handle this scenario correctly.  Until openstack fixes this problem, a dangling vm will be created.
 
We implemented this feature due to the need to assign fixedIp to VNFs. Deploying several instances of a given NSD with fixedIps, such as auto scaling case, is not considered.    We never tested fixedIp with auto scaling but we did test attempting to assign the same fixed IP address to a second VM.  It throws an exception and the VM is not created.   For right now, we would say fixedIp doesn’t support autoscaling.

**Comment by Urban123** [comment]
This is the feature that really lacks in Openbaton. We are onboarding our VNFs and most of them are not ready to be scaled, I know it's against the rules in the cloud, that we assign fixed IP, but most of our customers wish to configure firewall, routers in advance, so we have to provide fixed IP.

Right now we do that in VNFM (release the IP that was given to us, and assign the proper one. we do inside of the VNFM, because we don't won't to change the core of the OB much), but it would be really nice if could write that inside of the VNFD.

**Comment by RuthDevlaeminck** [comment]
This code has been merged into the main branch.
