### ISSUE TITLE
[bug] Refresh VIM

### ISSUE THREAD

**Issue by Rizwan-Qamar** [openbaton/NFVO#132]
Steps to reproduce:

1. Create a new Dummy network in Openstack
2. Refresh Vim in Openbaton  (This will work)
3. Delete the Network from OpenStack
4. Refresh Vim in Openbaton (Exception)

Idea is to invoke this line `networkRepository.delete(networks_old);` when **networks_old** has objects.
This should happen for images also, but I didn't check.

**Cannot delete or update a parent row: a foreign key constraint fails (`openbaton`.`vim_instance_networks`, CONSTRAINT `FK_e3jms0mwmxqihj9q6q0825idc` FOREIGN KEY (`networks_id`) REFERENCES `network` (`id`))**

**Comment by lorenzotomasini** [comment]
This can be reproduced just by refreshing the vim  instance test.

**Comment by Rizwan-Qamar** [comment]
@lorenzotomasini 
Although now there is no exception now, but this doesn't remove the entry of the network from the database.
Open new bug?

**Comment by Rizwan-Qamar** [comment]
@lorenzotomasini  Although now there is no exception now, but this doesn't remove the entry of the network  (network table) from the database.
Open new bug?
