### ISSUE TITLE
TOSCA example cannot be onboarded with 3.2.0 release

### ISSUE THREAD

**Issue by onurko** [openbaton/NFVO#139]
Hi,

CSAR file that i created according to the given example in https://github.com/openbaton/docs/blob/master/docs/tosca-CSAR-onboarding.md did not work. Checking logs shows us that there may be a TOSCA parser issue. I am attaching CSAR file and openbaton logs to retrieve onboarding problem.

BR,
[openbaton.txt](https://github.com/openbaton/NFVO/files/925903/openbaton.txt)
[iperf.csar.zip](https://github.com/openbaton/NFVO/files/925906/iperf.csar.zip)

Onur

**Comment by radoslavvlaskovski** [comment]
Hi Onur,

in the tosca definitions that you are trying to onboard the indentation of the "lifecycle" at both VNFs is wrong. "lifecycle" is a child of "interfaces" and as such it has to have a bigger indentation. 
You can check the csar file I am attaching here. 

[iperf.csar.zip](https://github.com/openbaton/NFVO/files/954760/iperf.csar.zip)


Cheers,

Radoslav

**Comment by onurko** [comment]
Hi Radoslav,

I prepeared a csar file and works fine, i think similar as yours. I am attaching sample csar file.

Thanks for your reply.

Kind Regards,

Onur

[iperf.csar.tar.gz](https://github.com/openbaton/NFVO/files/958228/iperf.csar.tar.gz)
