### ISSUE TITLE
Scale-Out PoP choice

### ISSUE THREAD

**Issue by ogozman** [openbaton/NFVO#141]
Right now the PoP for scale out is chosen randomly even if the PoP for initial deployment was not. This might lead to the problem in case, for example, test vim is present in the system (it is chosen and NFVO will try to deploy there).

**Comment by gc4rella** [comment]
still open? I consider it as a bug, therefore, I hope it could be fixed in upcoming 4.0.0 release.

**Comment by lorenzotomasini** [comment]
yes, I was assigning @radoslavvlaskovski but i can have a look into it, should not be hard. The GUI must be also updated ( @zohaibhassan122  ) then

**Comment by lorenzotomasini** [comment]
All references "_fix_" this "_bug_". As soon we are ready to change the api (not too much) i will merge
