### ISSUE TITLE
Wrong HTTP method

### ISSUE THREAD

**Issue by orkun34** [openbaton/NFVO#143]
Hello,

I found something during VNFD development on our side. When I implement **/vnf-descriptors/multipledelete** , it always throws error if I send HTTP method as DELETE and according to api doc 3.2.0 , it says that method is called with DELETE method.

![image](https://cloud.githubusercontent.com/assets/7378068/25471023/ca7936f8-2b2d-11e7-8b67-b051672d6c4a.png)

Here is log as well ; 
[vnf_log.txt](https://github.com/openbaton/NFVO/files/960710/vnf_log.txt)

However regarding this link http://get.openbaton.org/swagger-ui/#/ , method is called with POST which is worked on my side.

![image](https://cloud.githubusercontent.com/assets/7378068/25471083/0e9d4c20-2b2e-11e7-84c8-ef6556a11186.png)

I think valid one is the 2nd option.

**Comment by mpauls** [comment]
The POST method is the right method to use since it passes a json body that inlcudes the VNFD IDs to delete. Please use the swagger ui due to the fact that this one is created automatically from the API of the NFVO. Hence, the API doc will not be maintained anymore.
