### ISSUE TITLE
Launching a network service with REST API call

### ISSUE THREAD

**Issue by tahirokian** [openbaton/NFVO#144]
Hi,

Can you please help me regarding the launch of network service from on-boarded NSD using REST API calls. I am using the API at <http://get.openbaton.org/nfvo-api/#!/rest-network-service-record/createUsingPOST_1> to launch a service that was on-boarded using <http://get.openbaton.org/nfvo-api/#!/rest-csar/onboardNSDUsingPOST> but getting the error shown below. The id value used in `/api/v1/ns-records/id` is id of on-boarded NSD as instructed in the documentation. 

```
curl -X POST -v -H "Authorization: Bearer 8079ffd9-7510-44b8-9073-27edad75ec4d" -H "project-id: f7dfd326-6a0f-49ca-bc38-833f28d7b1e0" "http://172.16.255.3:8080/api/v1/ns-records/7453100f-bd5e-4d1f-a157-8e25b24b64c6"
*   Trying 172.16.255.3...
* Connected to 172.16.255.3 (172.16.255.3) port 8080 (#0)
> POST /api/v1/ns-records/7453100f-bd5e-4d1f-a157-8e25b24b64c6 HTTP/1.1
> Host: 172.16.255.3:8080
> User-Agent: curl/7.47.0
> Accept: */*
> Authorization: Bearer 8079ffd9-7510-44b8-9073-27edad75ec4d
> project-id: f7dfd326-6a0f-49ca-bc38-833f28d7b1e0
> 
< HTTP/1.1 404 Not Found
< Server: Apache-Coyote/1.1
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: POST, GET, OPTIONS, DELETE, PUT
< Access-Control-Max-Age: 3600
< Access-Control-Allow-Headers: x-requested-with, authorization, content-type, project-id
< X-Application-Context: NFVO OpenBaton
< Content-Type: application/json;charset=UTF-8
< Content-Length: 116
< Date: Thu, 27 Apr 2017 11:35:05 GMT
< 
{
  "code": "Not Found",
  "message": "No NetworkServiceRecord found with id 7453100f-bd5e-4d1f-a157-8e25b24b64c6"
* Connection #0 to host 172.16.255.3 left intact
}
```

**Comment by Rizwan-Qamar** [comment]
I think you need to provide the ID of the NSR (Network Service Record), not of the NSD.

**Comment by gc4rella** [comment]
still an open issue?

**Comment by tahirokian** [comment]
I think you need to check and update `NFVO api` documentation before closing the issue. Although, I have figured out the problem in my `curl` request. The api detail given at <http://get.openbaton.org/nfvo-api/#!/rest-network-service-record/createUsingPOST_1> does not say that `json object` in the request body is a `required` parameter (`even if its {}`) rather than optional (only the ones in `bold` are required). Also, content type should also be explicitly set as `application/json`. If you does not provide these, then you will get the error above. The curl commands that worked for me are:
`curl -X POST -v -H "Content-type: application/json" -H "Authorization: Bearer *token value*" -H "project-id: *project id*" -d '{}' "http://localhost:8080/api/v1/ns-records/*on-boarded nsd id*"`
 or
 `curl -X POST -v -H "Content-type: application/json" -H "Authorization: Bearer *token value*" -H "project-id: *project id*" -d '{"keys":[],"configurations":{"iperf-server":{"name":"","configurationParameters":[]},"iperf-client":{"name":"","configurationParameters":[]}},"vduVimInstances":{"VDU2":[],"VDU1":[]}}' "http://localhost:8080/api/v1/ns-records/*on-boarded nsd id*"` <http://get.openbaton.org/nfvo-api/#!/rest-network-service-record/createUsingPOST_1>

**Comment by lorenzotomasini** [comment]
Also this was a task of @radoslavvlaskovski, however i don't know the status. The idea was only to fix the [documentation](http://get.openbaton.org/swagger-ui/)
