### ISSUE TITLE
VNFC Start/Stop is not working properly

### ISSUE THREAD

**Issue by orkun34** [openbaton/NFVO#151]
Hello community,

Nowadays I'm working with VNFC as well in order to manage functionality of start/stop procedures. Whenever I take action about this , it seems that there is not problem on OpenBaton. 

Initial status ;
![image](https://cloud.githubusercontent.com/assets/7378068/25851595/0ccfa1a4-34cf-11e7-81f9-b1c19c4c91cd.png)
after stop;
![image](https://cloud.githubusercontent.com/assets/7378068/25851622/24519684-34cf-11e7-9b49-20ad88429ed2.png)
![image](https://cloud.githubusercontent.com/assets/7378068/25851634/2eebc11e-34cf-11e7-9246-e31f7c4ef103.png)

Below one is openbaton.log file output during action;
![image](https://cloud.githubusercontent.com/assets/7378068/25851692/6e23d664-34cf-11e7-8f9e-7618ee78a2f2.png)

Until this moment , there is not any problem.

However when I check OpenStack side , specified instance is still running although it has been stopped.
![image](https://cloud.githubusercontent.com/assets/7378068/25851765/b0c0a52e-34cf-11e7-9a3e-a0b80d023f50.png)

I tried to find issue but I couldn't find the reason why VM is still active.

The only guess that I found -I'm not pretty whether it's related or not- is that this start/stop is just used for scripts 

![image](https://cloud.githubusercontent.com/assets/7378068/25851906/50b38650-34d0-11e7-8cd3-039938fb488d.png)

Thanks in advance

**Comment by lorenzotomasini** [comment]
Hi,

I think your guess is right. Our start/stop focuses on the service running inside the VM. So if the _stop_ script is correctly executed, the nfvo + generic vnfm will assume that the service is correctly stopped. 

Does this answer help?

**Comment by erolozcan** [comment]
Is this behavior complaint with ETSI NFV specification? Will Openbaton have  support shutdown and start operation of a VNF  (VM)?

**Comment by lorenzotomasini** [comment]
This behaviour is connected with the vnfm you are using. A different vnfm than the generic one could have a different logic:

1. running the stop scripts
1. invoking the shutdown of the machine in the vim (saved from the first _instantiate_ message)
1. The start does then the same: start the machine if it is shut off

once the VM is shut off, you are then not able anymore to contact via the EMS, that will start automatically when the VM boots, so the re registration to the vnfm has to be handled but this only if you want to simply extend the generic vnfm. Another vnfm can choose a different way to communicate with the VM
