### ISSUE TITLE
Save of VNF issue

### ISSUE THREAD

**Issue by orkun34** [openbaton/NFVO#159]
There is a problem that I've faced during VNF creation.

Whenever I call vnf-save service , OB creates VNFD whereas it doesn't create any package hence VNFD doesn't provide all of its' proper functionality.

This is my sample VNFD
[sampleVNF.txt](https://github.com/openbaton/NFVO/files/1095811/sampleVNF.txt)
and sample NSD with same VNFD
[sampleVNF_NSD.txt](https://github.com/openbaton/NFVO/files/1095812/sampleVNF_NSD.txt)

There are 2 VNFD object at below image.

![image](https://user-images.githubusercontent.com/7378068/27449940-b07decf8-5792-11e7-81ed-a8b284668c5e.png)

    1 )  VNFD that was created during VNF save
    2 )   VNFD that was created during NSD save

The thing that I observed , it didn't create any timestamp for both "created" and "update".In addition whenever it's created via VNF service, I can't observe VNFPackage.

Last but not least , when I try to delete VNFD that was initialized via VNF API , below exception's thrown.

![image](https://user-images.githubusercontent.com/7378068/27450281-ea3cbaa4-5793-11e7-8c4f-357c9d8ca840.png)

OB log when VNFD deleted

![image](https://user-images.githubusercontent.com/7378068/27450425-58c16a24-5794-11e7-8d7d-8cea4ef2ece5.png)

Every VNF that is initialized via NSD works properly whereas whenever VNFDs' created via VNF services , it fails like above ones.

Thanks in advance

**Comment by gc4rella** [comment]
Indeed, it's a bug. thx for spotting. It should be fixed now, and will merged in develop after the review process.

**Comment by orkun34** [comment]
Va bene , grazie per il vostro sostegno

**Comment by gc4rella** [comment]
Please confirm that it works for you so that we can close this issue.
