### ISSUE TITLE
[Suggestion] Support for VDU dependencies

### ISSUE THREAD

**Issue by KLuka** [openbaton/NFVO#16]
Do you have any plans to support dependencies between VDUs in the same VNF? Syntax could look similar to current dependencies between VNFs.

This would come handy for cases like HA setup (active-standby pair) when we need to configure two VDUs that need to be aware of each other IP addresses.

**Comment by gc4rella** [comment]
This suggestion is accepted, and the implementation work will be evaluated in one of the next sprints

**Comment by marcellom** [comment]
This feature has not been introduced so far. If you are interested please create a pull request and we can evaluate it.
