### ISSUE TITLE
openbaton cannot orchestrate Fortinet VM

### ISSUE THREAD

**Issue by onurko** [openbaton/NFVO#166]
Hello,

Fortinet VNF can not be orchestrated from NFVO according to the missing agent implementation in Fortinet VM regarding security concerns. Do you have any roadmap for this integration or do you suggest any workaround for that?

BR.

**Comment by lorenzotomasini** [comment]
Hi,

why cannot be?

**Comment by onurko** [comment]
Hello Lorenzo,

This information is coming from Fortinet technical squad. They informed us that they dont implement agents according to the security aspects.

**Comment by lorenzotomasini** [comment]
This is then not an issue in Open Baton, more a limitation of the Fortinet solution. If you are asking for help in finding a workaround to that limitation, you will need to specify more details of your current approach. In that case feel free to reopen the issue with label _help wanted_ and providing the required info
