### ISSUE TITLE
OpenBaton OpenStack NSR error

### ISSUE THREAD

**Issue by alidiab90** [openbaton/NFVO#167]
when I launch the NSD the VNF record state goes from NULL to ERROR, giving this message, 

"ERROR:org.openbaton.common.vnfm_sdk.exception.VnfmSdkException: Not able to allocate Resources because: org.openbaton.exceptions.VimException: Not launched VM with hostname iperf-VNF1-6006064 successfully on VimInstance DC1. Caused by: Timeout of 300 second is reached and no answer was received, supposing that the plugin crashed".

**Comment by alidiab90** [comment]
okay, I attached it, thank you very much.
[log-plugin.docx](https://github.com/openbaton/NFVO/files/1138443/log-plugin.docx)

**Comment by alidiab90** [comment]
one more info: When I launch the NSD an instance got created in the OpenStack and got connected to the network written in the NSD and got Active too, but after some minutes an error occur in the OpenBaton NSR as I described above.

**Comment by lorenzotomasini** [comment]
there are many errors, all of them pretty clear.

can you restart everything and try to reproduce the mentioned error? Then providing the log in a [gist](https://gist.github.com/), (not docx please)

**Comment by alidiab90** [comment]
okay, I'll restart everything, and I will send you the results. Thanks you very much.

**Comment by alidiab90** [comment]
I restarted everything, I registered again the VIM (which is OpenStack), I allocated a floating IP in the OpenStack dashboard, I launched the NSD adding the PoP, an instance is created and connected to the network in the OpenStack, and I waited, in the NSR the state was NULL giving me these messages:
first: "GRANTED:All the resources that are contained in this VNFR were granted to be deployed in the chosen VIM(s)".
second: "ALLOCATE:All the resources that are contained in this VNFR were instantiated in the chosen VIM(s)".

after that the state gave an error: "ERROR:java.lang.RuntimeException: No EMS yet for host with extracted host ID: 6971264".

note: in the terminal I started the ems using this command: "sudo service ems start to start"  giving me "Starting EMS".

**Comment by alidiab90** [comment]
another note:
 I had this error ("ERROR:java.lang.RuntimeException: No EMS yet for host with extracted host ID: 6971264") yesterday so I thought that I should install the ems and I did that using these commands: 
    
    wget -O - http://get.openbaton.org/public.gpg.key | apt-key add -
    apt-get update
    apt-get install git -y
    apt-get install ems
    
After that, I launched again the NSD and I got the first error I told you about "ERROR:org.openbaton.common.vnfm_sdk.exception.VnfmSdkException: Not able to allocate Resources because: org.openbaton.exceptions.VimException: Not launched VM with hostname iperf-VNF1-6006064 successfully on VimInstance DC1. Caused by: Timeout of 300 second is reached and no answer was received, supposing that the plugin crashed". 

But now it is giving me gain the error of the ems "ERROR:java.lang.RuntimeException: No EMS yet for host with extracted host ID: 6971264".

**Comment by alidiab90** [comment]
@lorenzotomasini  can you help me?
can you tell me if this can be resolved or not?
if you can't now, we can talk another time, but tell me if it can be resolved or not, I'm a new user, excuse me for disturbing, Thanks.

**Comment by alidiab90** [comment]
@lorenzotomasini  help please!

**Comment by gc4rella** [comment]
Please double check the documentation:
http://openbaton.github.io/documentation/nfvo-configuration/

There is an important note you should probably consider. 

The problem is that in your installation the rabbitmq is not reachable from the ems because you configured it to localhost.

**Comment by alidiab90** [comment]
ok thank you alot, I will see, I'm a new user, I hope I can resolve this problem.
Thanksss

**Comment by alidiab90** [comment]
hello, I changed "nfvo.rabbit.brokerIp = localhost" to "nfvo.rabbit.brokerIp = <the rabbitmq broker ip>" in the "openbaton-nfvo.properties" file but it does not work, can somebody help me?

**Comment by alidiab90** [comment]
Excuse me, I changed it to "nfvo.rabbit.brokerIp = <the rabbitmq broker ip>", 
I wrote the exact phrase "<the rabbitmq broker ip>", should I put the IP (es: 192.128.**.***)?
if yes, which IP? where I get it?

**Comment by alidiab90** [comment]
<the rabbitmq broker ip> ?

**Comment by alidiab90** [comment]
the rabbitmq broker ip?

**Comment by gc4rella** [comment]
yes, as the variable name says. It should be the IP where rabbitmq can be reached from remotely.

**Comment by alidiab90** [comment]
Excuse me for disturbing, the OpenBaton IP eht1: 192.168.56.101:8080
I'm using OpenStack with the IP eth1: 192.168.56.103, should it be the IP where rabbitmq can be reached from remotely? I tried this IP 192.168.56.103 but it does not work.

**Comment by gc4rella** [comment]
what is the exact error you are getting? Have you restarted the nfvo/vnfm after applying those changes? Please check that you have also updated the vnfm configuration file with the new IP. 

In addition, please make sure that the VMs deployed in your openstack environment can reach that IP.

**Comment by alidiab90** [comment]
Good evening, I'm facing this problem when I launch the NSD , "ERROR:org.openbaton.common.vnfm_sdk.exception.VnfmSdkException: Not able to allocate Resources because: org.openbaton.exceptions.VimException: Not launched VM with hostname iperf-VNF1-6006064 successfully on VimInstance DC1. Caused by: Timeout of 300 second is reached and no answer was received, supposing that the plugin crashed".
I'm using OpenStack, when I launch the NSD an instance get created in the OpenStack dashboard and it get even active and I think it is reachable from the openbaton too because when I open the console of the instance that is created by OpenBaton it can ping the IP of the localhost of the OpenBaton, and if I associate to the instance a floating IP then it can be pinged from the console of openbaton, can you help me to see what is going and how can I solve it, thank you.

**Comment by alidiab90** [comment]
help please!!

**Comment by ranzpirat** [comment]
Hey @alidiab90 is the machine running your Open Baton installation reachable (not only ping) from the deployed VM's? So can you for example when you ssh into a deployed VM and execute
`curl http://IP_OF_YOUR_OPEN_BATON_INSTALLATION:8080` does it print some HTML output?

**Comment by alidiab90** [comment]
hii, I went to the VM , and I wrote "ssh http://192.168.56.105:8080", it printed some html output like:
</head>
<body> ....
note: my OpenStack and OpenBaton are on the same machine which OpenStack have the localhost which is "192.168.56.105" and OpenBaton have "192.168.56.105:8080"

**Comment by alidiab90** [comment]
** it printed some HTML output like (head, body div....)

**Comment by alidiab90** [comment]
in the VM I wrote : curl http://192.168.56.105:8080 , I made a mistake writing ssh in the previous comment, sorry

**Comment by ranzpirat** [comment]
Can you please attach the log files found in `/var/log/openbaton`

**Comment by alidiab90** [comment]
okay , thank you
[ems.receiver.log.docx](https://github.com/openbaton/NFVO/files/1337240/ems.receiver.log.docx)
[generic-vnfm.log.docx](https://github.com/openbaton/NFVO/files/1337242/generic-vnfm.log.docx)
[openbaton.log.docx](https://github.com/openbaton/NFVO/files/1337241/openbaton.log.docx)
[scriptsLog.docx](https://github.com/openbaton/NFVO/files/1337239/scriptsLog.docx)

**Comment by alidiab90** [comment]
trying to solve the problem I got this error: ERROR:org.openbaton.common.vnfm_sdk.exception.VnfmSdkException: Not able to allocate Resources because: org.openbaton.exceptions.VimException: Not launched VM with hostname iperf-VNF1-6363013 successfully on VimInstance DC1. Caused by: org.openbaton.exceptions.VimDriverException: Cannot assign FloatingIPs to VM with hostname: iperf-VNF1-6363013. No FloatingIPs left...

even if there is no floating IP used. And when I launch the NSD a floating IP got created.

**Comment by alidiab90** [comment]
okay, the same error as before, "Timeout of 300 second is reached and no answer was received, supposing that the plugin crashed".

**Comment by alidiab90** [comment]
Help please

**Comment by gc4rella** [comment]
hi @alidiab90 from the log you provided there is nothing which can help us understanding what's going on in your setup. Personally I don't understand your setup configuration, especially because you are running OpenStack and Open Baton on the same host. Are you using the same rabbitmq for both? Have you installed open baton using the bootstrap procedure?

**Comment by alidiab90** [comment]
hi @gc4rella , okay, yes I installed OpenBaton from the bootstrap procedure, I think I'm using the same rabbitmq for both, how can I know? I run openstack and openbaton on the same host because the VM in the openstack can reach only its host ip that's why I run openbaton on the same host so the VM can reach openbaton, when I launch the NSD from the openbaton, an instance(VM) got created in the openstack but the NSR in the openbaton did not get ACTIVE, it stays 5 mins in the NULL state before it changes to ERROR state giving  "Timeout of 300 second is reached and no answer was received, supposing that the plugin crashed", note: the VM(instance) can be reached from the host IP only by giving a floating IP to it.

**Comment by gc4rella** [comment]
@alidiab90 now things are a bit more clear. The problem you are having seems to be related with the communication between the openstack driver and the NFVO. Probably because of the co-location of OpenStack and Open Baton on the same host, thus using the same rabbitmq. We never tested the scenario where both openstack and open baton run on the same host. My suggestion is to install open baton on a different host than openstack. For instance, you could install open baton in a vm on the tenant where you want to deploy your VNFs. This was tested several times, and should work without any issues. When running the bootstrap, you should assign the floating IP when asking to insert the rabbitmq IP.

**Comment by alidiab90** [comment]
@gc4rella Excuse me, first I tried to install openbaton in a different host than openstack, when I launched the NSD in openbaton an instance(VM) got created in the openstack dashboard over the network I mentioned in the NSD(json), but the NSR had NULL state and after a few minutes turns to get an ERROR state giving this message "ERROR:java.lang.RuntimeException: No EMS yet for host with extracted host ID: 6971264", I changed this "nfvo.rabbit.brokerIp = localhost" to this "nfvo.rabbit.brokerIp = 192.168.56.105(the host IP of openbaton)" as you told me before but nothing happened it still gave me the same error(no ems yet...), when I had the openbaton in different host than openstack the vm(instance) in the openstack could not reach the open baton and I think thats why it give me that error (no ems yet...), but when I put them in the same host so the vm(instance) reache the host where openbaton installed that error did not appear any more, any way I did not understand well this "For instance, you could install open baton in a vm on the tenant where you want to deploy your VNFs" , where I should install openbaton?

**Comment by gc4rella** [comment]
you can start a VM in OpenStack, and install open baton there. The error you got before is due to the fact that the VMs deployed via open baton couldn't reach the rabbitmq, so you need to ensure that connectivity works between VMs and the host where open baton (rabbitmq) run, and you don't have any ports (mainly 5672) blocked

**Comment by alidiab90** [comment]
when I start VM in OpenStack I can't install openbaton via bootstrap procedure (sh <(curl -s http://get.openbaton.org/bootstrap) release ), how it can be installed in the VM I don't know :( .
And yes the error I got before was that there is no connectivity between VMs in openstack and openbaton, I could not reach the openbaton IP from the VM openstack, because of that I installed the openbaton in the same host as openstack so it can be reachable, but an error got as I explained before.

**Comment by alidiab90** [comment]
Hi again, an error occured:
"Caused by: org.openbaton.exceptions.VimDriverException: Cannot assign FloatingIPs to VM with hostname: iperf-VNF1-6363013. No FloatingIPs left.."

Any help!!

**Comment by alidiab90** [comment]
this error come when I launch the NSD, in the json "floatingIp":"random" I tried random it gave me this error "Caused by: org.openbaton.exceptions.VimDriverException: Cannot assign FloatingIPs to VM with hostname: iperf-VNF1-6363013. No FloatingIPs left..", when I try to allocate a floating Ip like "floatingIp":"192.168.56.115" it let me wait 300 seconds and then give me this error "Caused by: Timeout of 300 second is reached and no answer was received, supposing that the plugin crashed".

Any help!!

**Comment by ranzpirat** [comment]
Is it possible for you to allocate and assign floating ip's manually in your openstack deployment?

**Comment by alidiab90** [comment]
hi, yes it is, I can assign floating ip's manually and it can be reached from all external hosts.

**Comment by alidiab90** [comment]
One note: when it give me this error "Cannot assign FloatingIPs to VM with hostname: iperf-VNF1-6363013. No FloatingIPs left.." and when I go and check the floatingIps section in OpenStack I find that a floatingIp got created.

**Comment by alidiab90** [comment]
Another note: this error(no floatings ips left..) happens when I launch the NSD of "NSD iperf + floatingIPs",
but when I try to launch the NSD of "NSD iperf + privateIPs" the "Last Executed Action" of NSR changes from "Granted" to "Allocate" but finally the state go to error giving this "No EMS yet for host with extracted host ID: 7198754", any help!

**Comment by alidiab90** [comment]
?

**Comment by mf3d3r** [comment]
maybe you are facing the same situation like I did. I got the same error and the solution was to change a value of a timer in the vnfm.properties file.
This happens when the instantiation-process lasts longer as the value of this timer.
In my case the instantiation-process lasts 960seconds and the standard value in the properties-file is set to 500s.
Thats the reason why this error message CAN happen...

**Comment by darguna** [comment]
> maybe you are facing the same situation like I did. I got the same error and the solution was to change a value of a timer in the vnfm.properties file.
> This happens when the instantiation-process lasts longer as the value of this timer.
> In my case the instantiation-process lasts 960seconds and the standard value in the properties-file is set to 500s.
> Thats a reason why this error message CAN happen...

Hi,
This may sound stupid, but I am not able to locate the vnfm.properties file. Can you tell me where it could be located?
Also, I am getting the same error 
ERROR:org.openbaton.common.vnfm_sdk.exception.VnfmSdkException: Not able to allocate Resources because: Not launched VM with hostname iperf-client-4178998 successfully on VimInstance pop-1. Caused by: org.openbaton.exceptions.VimDriverException: [OpenStack] 500: Exceeded maximum number of retries. Exhausted all hosts available for retrying build failures for instance 0bf22df0-b984-4313-875a-e0cd02df518d.

Can you tell me how you fixed it?

**Comment by marcellom** [comment]
Hi @darguna, the property file of the generic-vnfm is this one: https://github.com/openbaton/generic-vnfm/blob/master/src/main/resources/application.properties
But depending on how you installed it, there are different ways of changing the properties. Did you use docker-compose installation? Or did you clone the repo?
Anyway from your log, it looks like a problem of available resources in OpenStack. Try to deploy a virtual machine manually and check if everything works properly.
Finally, please use the email users@openbaton.org for additional support
