### ISSUE TITLE
[Suggestion] Affinity support

### ISSUE THREAD

**Issue by KLuka** [openbaton/NFVO#17]
Do you have any plans to support "affinity" and "anti-affinity" paramteres in VNFD?

For our case we would need to specify that two VDUs (active-standby pair) are not on the same compute node, so we can expect better availability in case of hardware failures.

Also in some cases it would be desired that two or more VDUs are deployed on same compute node, so that network traffic over cloud can be reduced.

> Anti-affinity can be used to support availability, survivability and performance needs with respect to 
> virtualised resources. 

Source: http://www.etsi.org/deliver/etsi_gs/NFV-IFA/001_099/010/02.01.01_60/gs_NFV-IFA010v020101p.pdf

**Comment by gc4rella** [comment]
For the moment we are relying on the nova scheduler for deciding vdu placement. We'll evaluate the required changes on the VIM interface in order to support this functionality.

**Comment by marcellom** [comment]
At the moment you can select on which availability zone to deploy a VNF. But we are not providing a specific affinity parameter in the VNFD. Thanks for the suggestion
