### ISSUE TITLE
Rethink delete VNFD from NSD method

### ISSUE THREAD

**Issue by ThomasBri** [openbaton/NFVO#172]
Currently, the `deleteVnfDescriptor(String idNsd, String idVnfd, String projectId)` method in the NetworkServiceDescriptorManagement class is not working.
You cannot delete the VNFD because the NSD is still onboarded and if you delete the NSD first, it throws a NullPointerException.

This method is probably a leftover from the time when the VNFDs did not have their own management class and maybe it is better to alter the behavior to e.g. just removing the VNFD from the NSD but keeping it stored in Open Baton, in this way updating the NSD.

**Comment by ThomasBri** [comment]
Actually the whole `/api/v1/ns-descriptors/<nsd_id>/<subcomponent>` api path is buggy and should be reviewed.

**Comment by marcellom** [comment]
This https://github.com/openbaton/NFVO/pull/239 allows to delete a VNFD from a NSD. The VNFD is then removed from the NFVO. This issue is also related to https://github.com/openbaton/NFVO/issues/197.

**Comment by marcellom** [comment]
https://github.com/openbaton/NFVO/pull/239 has been merged, I close this issue.
