### ISSUE TITLE
NSD without VNFDs results in confusing error

### ISSUE THREAD

**Issue by szengerle** [openbaton/NFVO#184]
I had forgot to add the VNFD-Ids into the NSD before I uploaded it. The result was an error: No VNFManagers were found. Error code: 404
Because I used the wrong file and the message hasn't anything to do with the actually error, I searched at the wrong place and troubleshooted in NSDUtils.java. After I added some trace infos I found the error of the missing IDs. My suggestion is to validate if VNFDs exist in the NSD. 

Would be core/core-impl/src/main/java/org/openbaton/nfvo/core/api/NetworkServiceDescriptorManagement.java during onboard/update method the right place to do such a validation? Then I can create a pull request.

**Comment by gc4rella** [comment]
Hi @szengerle, I can confirm the issue, however, it is only happening when you pass an empty VNFD json object. If you pass: 

* ` "vnfd": [ ],` seems to be handled correctly with an error message
* ` "vnfd": [{}],` seems to be the issue you are referring to. I think such check should also be added, so please go ahead with pull request. 

Thx

**Comment by szengerle** [comment]
I mean `"vnfd": [ ]` and it was already done in the latest develop HEAD. `"vnfd": [{}]` throw also exception. So, nothing todo.
