### ISSUE TITLE
[Suggestion] Support for parameterized NSD/VNFD

### ISSUE THREAD

**Issue by KLuka** [openbaton/NFVO#19]
It would be very useful if user could provide some parameters at NSD/VNFD instantiation time. 
That would mean that one NSD/VNFD can be instantiated in different ways, with some minimal
changes. Similar to OpenStack HEAT template input parameters.

For example user could decide what OpenStack network to use for his VDU at instantiaton time. 
There would be no need to re-upload the VNFD package, when different network is desired.

Example VNFD:

```
  "connection_point":[
    {
      "floatingIp":"randomIp",
      "virtual_link_reference": {"get_input": "vdu_network_name"}
    }
  ]
```

PS: this suggestion was already posted on mailing list, I am just posting it here for easier tracking.

**Comment by mpauls** [comment]
We introduced some parameters which can be passed at instantiation time. Available parameters at the moment are:
- which PoP to deploy certain VNFs
- keys to use for accessing VMs
- configuration parameters adding to the VNFs
