### ISSUE TITLE
registering PoP

### ISSUE THREAD

**Issue by myself96** [openbaton/NFVO#192]
Hollo
can anybody help be about this,
 what should i do for registering a PoP after installing openbaton by docker(i checked in dashboard for openstack and i seems ,it is installed).......actually I don't know what to set for authurl,tenant and key pair(H made only a key in dashbourd, but I did nothing with that)...........I tried somethings but got these errors:Refreshing VIM caused following error: org.openbaton.exceptions.VimException: Not listed Images successfully of VimInstance puria. Caused by: org.openbaton.exceptions.VimDriverException: Connection refused (Connection refused) Code: 422...................................................or:Refreshing VIM caused following error: org.openbaton.exceptions.VimException: Not listed Images successfully of VimInstance puria. Caused by: org.openbaton.exceptions.VimDriverException Code: 422

Thanks

**Comment by lorenzotomasini** [comment]
have a look into the docs, in particular:

http://openbaton.github.io/documentation/vim-instance/
