### ISSUE TITLE
remove VNFD from NSD

### ISSUE THREAD

**Issue by gc4rella** [openbaton/NFVO#197]
It seems that the dashboard offers the possibility to remove the VNFD from the NSD, however when trying to do that, I get an error message: `undefined. Error code: 422`

I assume is a bug. no records was active using that descriptor.

**Comment by lorenzotomasini** [comment]
Can we close this? @marcellom @gc4rella

**Comment by marcellom** [comment]
depends if you want to merge #239

**Comment by marcellom** [comment]
https://github.com/openbaton/NFVO/pull/239 has been merged, I close this issue.
