### ISSUE TITLE
creating NSR in openbaton on an openstack instance giving error "imageubuntu is not contained into the images of the vimInstance chosen"

### ISSUE THREAD

**Issue by sipian** [openbaton/NFVO#237]
I am installing OpenBaton on an instance on a private network in OpenStack (Pike release). The screenshot of the network-topology is attached below 
![image](https://user-images.githubusercontent.com/15672091/33795095-2747a778-dd00-11e7-95cb-d5106cc00b54.png)

On changing the routing table of my OpenStack machine I can ping as well as ssh into this instance from my OpenStack machine terminal. I can also ping my OpenStack machine from this instance 

Now I created a POP in OpenBaton as follows
```json
{  
   "name":"pop",
   "authUrl":"http://<openstack-server-ip>/identity/v3",
   "tenant":"673bf2477d4a48eeb32433b175dd1c19",
   "username":"admin",
   "password":"xxxxx",
   "keyPair":"openbatonkeypair",
   "securityGroups":[  
      "default"
   ],
   "type":"openstack",
}
```
Now I am trying to create the iPerf Network Service as given [here](https://openbaton.github.io/documentation/iperf-NSR/). I am using [this](https://gist.github.com/sipian/0594f98f4ddbea59a4bbc4368c87b654) JSON as my Network Service Descriptor.

But I am always getting an error as

> Exception was thrown -> Return message: Regarding the VirtualNetworkFunctionDescriptor iperf-client: in one of the VirtualDeploymentUnit, imageubuntu is not contained into the images of the vimInstance chosen. Please choose one from: [] or from []

I am attaching a screenshot of the images in my OpenStack project
![image](https://user-images.githubusercontent.com/15672091/33795314-1e7ade80-dd05-11e7-902c-fec3e5b8e9b6.png)

I have uploaded [openbaton.log](https://gist.github.com/sipian/8f722fbcb4abff77288b221da6b74471) and [generic-vnfm.log](https://gist.github.com/sipian/8d50df6d165c773c82ae4533f8af317a)

**Comment by gc4rella** [comment]
hi @sipian could you please provide also the logs of the openstack4j vim driver/plugin? if you have used the bootstrap (binary) installation, they should also be located somewhere in /var/log/openbaton/. 

My assumption is that your OpenStack setup uses glance v3 APIs, which probably are not supported by the openstack4j vim driver (but there were other users making that work..).

**Comment by sipian** [comment]
Hi @gc4rella ,
These are the log files that I are there in /var/log/openbaton/plugins
[plugin-openstack_2017-12-09_10-50-03.log](https://gist.github.com/sipian/168e2b28d5eb0faecb9de22d1b415bc0)
[plugin-test_2017-12-09_10-44-42.log](https://gist.github.com/sipian/95b293f8f32b25351a9d46fc6154a6a5)
[plugin-test_2017-12-09_10-45-40.log](https://gist.github.com/sipian/8a100999e751d946e553bf519e681e68)
[plugin-test_2017-12-09_10-50-02.log](https://gist.github.com/sipian/4637c4faa321825ef5d75bac72dc3dfb)

**Comment by sipian** [comment]
The problem went away after I installed OpenStack Newton release.
Thanks @gc4rella for your help.

**Comment by gc4rella** [comment]
OK, as said the problem should be due to the new version of the glance APIs. We are working on it, and we'll make sure they will be supported by default in upcoming versions of the plugin.
