### ISSUE TITLE
Cannot load driver class: org.mariadb.jdbc.Driver while building NFVO-3.2.0

### ISSUE THREAD

**Issue by sipian** [openbaton/NFVO#241]
I need to work with NFVO-3.0.1 and Genereic-VNFM-3.0.0 for a project.
But on setting these versions in the config file and running 
**./[bootstrap](https://github.com/openbaton/bootstrap/blob/develop/bootstrap) develop --config-file=/home/ubuntu/config** NFVO is not staring on port 8080 and I am getting the following error message in my openbaton.log

> Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceAutoConfiguration$NonEmbeddedConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.IllegalStateException: Cannot load driver class: org.mariadb.jdbc.Driver 

I am facing this same issue if I build NFVO-3.2.0 and Genereic-VNFM-3.2.0

Could someone tell me what parameters need to be changed to make this work ?

**Comment by gc4rella** [comment]
You could check an older version of the bootstrap available at: http://get.openbaton.org/bootstraps/

I assume that the latest bootstrap does not support older versions, especially source code installation.
