### ISSUE TITLE
apt-get upgrade issues

### ISSUE THREAD

**Issue by gc4rella** [openbaton/NFVO#248]
After upgrading from 5.1.2 to 5.1.3 the config file got almost corrupted with lot of duplicated entries and many parameters overwritten. For instance: 

`# after a plugin is registered specify the delay after which the refresh of already onboarded vim instances will be invoked ( <= 0 to disable it)
management.security.enabled=false

management.security.enabled=false
management.security.enabled=false

management.security.enabled=false
management.security.enabled=false
management.security.enabled=false
management.security.enabled=false
management.security.enabled=false

management.security.enabled=false
management.security.enabled=false

management.security.enabled=false
management.security.enabled=false

management.security.enabled=false

management.security.enabled=false
management.security.enabled=false
management.security.enabled=false

# Thread pool executor configuration
# for info see http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/scheduling/concurrent/ThreadPoolTaskExecutor.html
# We suggest to keep the queuecapacity and maxpoolsize values unless you have a good reason to change them.
management.security.enabled=false
management.security.enabled=false
management.security.enabled=false
# default is Integer.MAX_VALUE
management.security.enabled=false

management.security.enabled=false
management.security.enabled=false

# Enable SSL
management.security.enabled=false
management.security.enabled=false
management.security.enabled=false
management.security.enabled=false
management.security.enabled=false
management.security.enabled=false
management.security.enabled=false`

**Comment by mpauls** [comment]
I assume this was fixed by PR #258
