### ISSUE TITLE
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 3 path $[0]

### ISSUE THREAD

**Issue by gaurav1510** [openbaton/NFVO#249]
I am using **3.0.1 version of OpenBaton NFVO**, and **3.0.0 version of Generic VNFM** to deploy VNFs (iperf server and client).
However, I face this error while launching NSR -
![image](https://user-images.githubusercontent.com/26245143/34338297-4119958c-e98d-11e7-8d89-28612a32d8d1.png)
While using the same NSR JSON file in the latest versions of openbaton, I can do it flawlessly.
Are the changes to be made in JSON, or is the 3.0.1 version of OPENBATON NFVO functional??

I am using the below JSOn to do this -

_{
  "name":"NSD iperf + privateIPs",
  "vendor":"FOKUS",
  "version":"1.0",
  "vld":[
    {
      "name":"private"
    }
  ],
  "vnfd":[
    {
      "name":"iperf-client",
      "vendor":"FOKUS",
      "version":"1.0",
      "lifecycle_event":[
        {
          "event":"CONFIGURE",
          "lifecycle_events":[
            "server_configure.sh"
          ]
        },
        {
          "event":"INSTANTIATE",
          "lifecycle_events":[
            "install.sh"
          ]
        }
      ],
      "vdu":[
        {
          "vm_image":[
            "ubuntu"
          ],
          "scale_in_out":1,
          "vnfc":[
            {
              "connection_point":[
                {
                  "virtual_link_reference":"private",
                  "interfaceId":0
                }
              ]
            }
          ],
          "vimInstanceName":["test"]
        }
      ],
      "virtual_link":[
        {
          "name":"private"
        }
      ],
      "deployment_flavour":[
        {
          "flavour_key":"m1.small"
        }
      ],
      "type":"client",
      "endpoint":"generic",
      "vnfPackageLocation":"https://github.com/openbaton/vnf-scripts.git"
    },
    {
      "name":"iperf-server",
      "vendor":"FOKUS",
      "version":"1.0",
      "lifecycle_event":[
        {
          "event":"INSTANTIATE",
          "lifecycle_events":[
            "install.sh",
            "install-srv.sh"
          ]
        }
      ],
      "virtual_link":[
        {
          "name":"private"
        }
      ],
      "vdu":[
        {
          "vm_image":[
            "ubuntu"
          ],
          "scale_in_out":1,
          "vnfc":[
            {
              "connection_point":[
                {
                  "virtual_link_reference":"private",
                  "interfaceId":0
                }
              ]
            }
          ],
          "vimInstanceName":["test"]
        }
      ],
      "deployment_flavour":[
        {
          "flavour_key":"m1.small"
        }
      ],
      "type":"server",
      "endpoint":"generic",
      "vnfPackageLocation":"https://github.com/openbaton/vnf-scripts.git"
    }
  ],
  "vnf_dependency":[
    {
      "source":{
        "name":"iperf-server"
      },
      "target":{
        "name":"iperf-client"
      },
      "parameters":[
        "private"
      ]
    }
  ]
}_

**Comment by gc4rella** [comment]
Your issue is most probably due to mismatching versions between the NFVO and the generic VNFM.
