### ISSUE TITLE
Openbaton fails to start

### ISSUE THREAD

**Issue by p4pe** [openbaton/NFVO#252]
Hello everyone,
I'm newbie on this field, I tried to install openbaton on a Ubuntu machine. I installed it from docker container.

As I can see the image is running, but I cannot connect it to localhost:8080
![unnamed](https://user-images.githubusercontent.com/35313995/34798859-474317ea-f666-11e7-8fac-c8b43c0348cd.png)

Any ideas?

Thank you in advance

**Comment by gc4rella** [comment]
Hi @p4pe If you use a VM you can’t connect to the dashboard via localhost, you should use the remote VM IP. Please checkout this video which shows the full process: https://asciinema.org/a/156689
