### ISSUE TITLE
no ems for hostame : error

### ISSUE THREAD

**Issue by gaurav1510** [openbaton/NFVO#278]
Hi sir,
I am using NFVO 3.0 and appropriate corresponding generic-VNFM.
While I spawn new VNFs using openbaton GUI, each NS Descriptor completes it's ALLOCATE and GRANT phase.
However, then I get an error - **no ems for hostame** .....
Since VNF has completed its GRANT and ALLOCATE phase, VM is created and I can login it too.
And logs (/var/log/openbaton/ems-receiver.log) say that -
_INFO:__main__:EMS configuration paramters are hostname: client-565, username: admin, password: *****, autodel: true, heartbeat: 120, exchange name: openbaton-exchange
INFO:pika.adapters.base_connection:Connecting to 192.168.136.84:5672
ERROR:pika.adapters.base_connection:Connection to 192.168.136.84:5672 failed: timeout
WARNING:pika.connection:Could not connect, 0 attempts left_

**Comment by RuthDevlaeminck** [comment]
@gaurav1510 
It looks like there is a communication issue between your Open Baton box and your generated VM.  You might first check to make sure that you can reach the Open Baton ip address from your VM by executing 

`ping 192.168.136.84`

on your VM.  If that succeeds make sure that any security rules/firewall rules are opened on your Open Baton box to allow ingress on port 5672.

**Comment by gaurav1510** [comment]
Yes sir,
The IP address and even the port is reachable from the VM.
However, _nmap_ to the IP 192.168.136.84 does not return 5672 port.
![image](https://user-images.githubusercontent.com/26245143/36865348-4a31edf2-1db5-11e8-9a17-a45b9db4ebe8.png)

And also I have enabled all the security rules -
![image](https://user-images.githubusercontent.com/26245143/36865251-f5359196-1db4-11e8-9feb-b0f522ac6ec7.png)

Thanks for your previous reply.

**Comment by RuthDevlaeminck** [comment]
On your Open Baton box can you see if port 5672 is open?  On ubuntu the command is 

`netstat -an | grep 5672`

**Comment by gaurav1510** [comment]
tcp6       0      0 :::5672                 :::*                    LISTEN     
is the output

yes sir

**Comment by RuthDevlaeminck** [comment]
You have unfortunately exhausted my knowledge of how to fix this issue but the problem is that the VM cannot connect to the Open Baton box on port 5672.  You might want to get in touch with someone more familiar with your network and see if they can help you debug the issue.

**Comment by sipian** [comment]
The fix to this problem is that timeout value was less for ems in generic-vnfm.
To change this update [vnfm.ems.start.timeout](https://github.com/openbaton/generic-vnfm/blob/master/src/main/resources/application.properties#L31) in application.properties for generic-vnfm.

**Comment by marcellom** [comment]
Closed due to inactivity
