### ISSUE TITLE
Give scripts all IP addresses

### ISSUE THREAD

**Issue by RuthDevlaeminck** [openbaton/NFVO#280]
Currently if there is more than one interface (openstack port) on a single network only the first interfaces's IP address is available to the scripts as $network_name.   If there is more than one subnet associated with a particular network (i.e. IPv4 and IPv6) openstack assigns IP addresses from both but the value of $network_name in the scripts is randomly assigned between the two.

Propose having a new variable $network_name_ips that contains all of the IP addresses assigned on that network.  Additionally propose that it include the interface number (if assigned in the vnfd.json file) and the subnet name.

**Comment by marcellom** [comment]
closed due to inactivity
