### ISSUE TITLE
Business Continuity - OpenBaton

### ISSUE THREAD

**Issue by onurko** [openbaton/NFVO#297]
Hello,

Is there any Business Continuity mechanism for OpenBaton itself? Is there any way to scale or make redundant for network deployments?

BR.

Onur

**Comment by marcellom** [comment]
Hi, I answer you reusing an answer of my colleague on our Gitter channel. 
We are not providing any specific setup for Business Continuity or High Availability out of the box. But regarding HA, we know for sure that every main component can horizontally scale (NFVO, all VNFMs, all Plugins) and the non-OB components (MariaDB, rabbitmq) provide some clustered solution for that purpose.
If you need more info please write to users@openbaton.org or use the Gitter channel https://gitter.im/openbaton/NFVO.
BR,
Marcello
