### ISSUE TITLE
Enabling a new service error

### ISSUE THREAD

**Issue by aydinhus** [openbaton/NFVO#305]
Hi everyone,

ASE requires a service token which is used runtime to interact with the NFVO. When enabling new service on GUI it gives an error;

**Please input the service name and role properly. One of them is missing or entered incorrect.**
Also tried on CLI, it gives weird output and can able to see created service on GUI but can't get service key.
![resim](https://user-images.githubusercontent.com/6062553/48848888-32634f00-edb6-11e8-8299-b5367257da49.png)

http://openbaton.github.io/documentation/services/

Any thoughts?
Thanks,

**Comment by aydinhus** [comment]
Looks like related with nfvo version. I tried setup for 5.0.0 and it's working.

**Comment by ThomasBri** [comment]
Which version have you been using before?

**Comment by aydinhus** [comment]
> 
> 
> Which version have you been using before?

 NFVO version: 5.2.1

**Comment by mpauls** [comment]
You may try again with version 6.0.0 or latest if this issue still exists for you. The problem with the CLI shall be fixed in the newer release.
