### ISSUE TITLE
Allocate Resource Improper Exception Handling

### ISSUE THREAD

**Issue by Rizwan-Qamar** [openbaton/NFVO#32]
`

        try {

            for (VirtualDeploymentUnit vdu : virtualNetworkFunctionRecord.getVdu()) {
                VimInstance vimInstance = vims.get(vdu.getId());

                if (vimInstance == null)
                    throw new NullPointerException("Our algorithms are too complex, even for us, this is what abnormal IQ means :(");
                try {
                    if(vdu.getCreate_and_attach_volumes()!=null){
                        for (CreateVolume createVolume : vdu.getCreate_and_attach_volumes()) {
                            vdu.getVolumes_id().add(vimManagement.createVolume(vimInstance.getId(), createVolume, vdu.getProjectId()).getExtId());
                        }
                    }
                    ids.add(resourceManagement.allocate(vdu, virtualNetworkFunctionRecord, vimInstance, vdu.getUser_data()));

                }
                catch (VimException e) {
                    e.printStackTrace();
                    log.error(e.getMessage());
                    LifecycleEvent lifecycleEvent = new LifecycleEvent();
                    lifecycleEvent.setEvent(Event.ERROR);
                    VNFCInstance vnfcInstance = e.getVnfcInstance();

                    if (vnfcInstance != null) {
                        log.info("The VM was not correctly deployed. ExtId is: " + vnfcInstance.getVc_id());
                        log.debug("Details are: " + vnfcInstance);
                        vdu.getVnfc_instance().add(vnfcInstance);
                    }
                    virtualNetworkFunctionRecord.getLifecycle_event_history().add(lifecycleEvent);
                    saveVirtualNetworkFunctionRecord();
                    OrVnfmErrorMessage nfvMessage = new OrVnfmErrorMessage(virtualNetworkFunctionRecord, e.getMessage());
                    return nfvMessage;
                }
            }

        } catch (VimDriverException e) {
            e.printStackTrace();
            log.error(e.getMessage());
            LifecycleEvent lifecycleEvent = new LifecycleEvent();
            lifecycleEvent.setEvent(Event.ERROR);
            virtualNetworkFunctionRecord.getLifecycle_event_history().add(lifecycleEvent);
            virtualNetworkFunctionRecord.setStatus(Status.ERROR);
            saveVirtualNetworkFunctionRecord();
            OrVnfmErrorMessage nfvMessage = new OrVnfmErrorMessage(virtualNetworkFunctionRecord, e.getMessage());
            return nfvMessage;
        }`

1. These Catch blocks never run, because "resourceManagement.allocate" is an Async method and exception thrown from Async is caught by Spring. Spring then places the exception in "cause" property and throws "ExecutionException". (Right now it is caught in AbstractTask Class)

2. Catch block should not return, as in case of mutiple VDUs throwing exception only first one will save the "vnfcInstance" and return statement will stop the execution for successive VDUs (making them undeletable from the VIM)

**Comment by lorenzotomasini** [comment]
Thanks @Rizwan-Qamar, we fixed this issue in our develop branch
