### ISSUE TITLE
test task creates tosca tar and does not delete them

### ISSUE THREAD

**Issue by lorenzotomasini** [openbaton/NFVO#33]
when running 

``` bash
gradle test
```

the tosca tests create some tar but in the end they are not removed, they show as new file in git ready to be added. Let's try to avoid to upload to the repo by mistake removing them after the tests are executed

**Comment by lorenzotomasini** [comment]
Can we close this?

**Comment by radoslavvlaskovski** [comment]
Yes. It was fixed.
