### ISSUE TITLE
Nullpointerexception using the latest release

### ISSUE THREAD

**Issue by jolly2** [openbaton/NFVO#41]
Trying to integrate openbaton with openstack VIM. Using the recently release openbaton. Trying to test iperf. I was able to upload and deploy the  iperf client and server from openbaton. Both of them run successfully. After executing the install script, it goes through GRANT and ALLOCATE events successfully. After that it errors out with nullpointer exception. It looks like it is expecting some configurationparameter provides. That is empty in NSD record. Is there anything that needs to be set in the config?

VNF Record Information
 Overview    NS Records    NSR: NSD iperf + privateIPs    VNF Records   VNF Record
Name	iperf-client
Status	ERROR
Current Task	error
Project ID	8cd4b0f2-54de-49e8-a7a9-35ca53b2b4da
Type	client
Version	1.0
Endpoint	generic
Cyclic Dependency	false
Provides	{"id":"5ce5ab8a-4679-47d9-89a1-a734eac26790","version":0,"configurationParameters":[],"name":"provides"}
Package ID	cb7338c0-dec3-4aa9-9653-7b1c5828dd28
Parent NSR	ff653ae9-32bb-480e-9e42-438524170f1e
Project ID	8cd4b0f2-54de-49e8-a7a9-35ca53b2b4da

Thanks

**Comment by gc4rella** [comment]
hi @jolly2 it would be helpful if you could provide the initial NSD (remove all scripts if you don't want to show them here), and in particular the logs from the orchestrator including the error message. 

One usual problem is that the rabbitmq is not set correctly. Please refer to the openbaton documentation here: http://openbaton.github.io/documentation/nfvo-configuration/

In particular: 
> 1) By default RabbitMQ is installed on the host of the NFVO. Be aware of the fact that if you want your VNFM to be executed on a different host, you will need RabbitMQ to be reachable also from the outside.
> So when you want to deploy a VNF (EMS) in a VM which runs on a different host than the NFVO, you will need to configure the rabbitmq endpoint (nfvo.rabbit.brokerIp) with the real IP of the NFVO host (instead of localhost).

**Comment by jolly2** [comment]
Thanks for the reply.
In the setup, RabbitMq is reachable from from a VM (VNF VM) and ems also successfully reach rabbitmq and starts inside the VM without any problem. The problem is, after launching,  openbaton does not seem to wait till ems is downloaded into VM and starts running (mine is a little slow connection..takes about 5 mins for a VM to start and download ems and run it) and goes to the final state of ERROR (no ems for hostname) and does not make an effort to try again and I did not see any option to continue from Granted state. But, I see only start/stop, which does not help without it going through Instatitate state (at which point it should install iperf and screen). Resume button does not seem to work. It throws java exception error (i am not sure what resume does).
Lifecycle Event
Id 	event 	lifecycle events 
04874e1f-b3cd-486e-9594-8cca66f35922	ALLOCATE	
bf9489b9-3d6a-4ed7-8c59-f8dd1bc5f51f	GRANTED	
ffdc270e-b7fd-496d-9f7f-6276183e81e5	ERROR	

Thanks!

**Comment by gc4rella** [comment]
Please modify the timeout value for waiting more time for EMS: 
https://github.com/openbaton/generic-vnfm/blob/master/src/main/resources/application.properties#L29

In case you use the source code and you don't have an external configuration file (located at: /opt/openbaton) you will need to re-compile the project in order to apply this change.

**Comment by jolly2** [comment]
Increasing the timeout period worked. Thanks !
