### ISSUE TITLE
Floating IP is not getting attached to VM instance even though Floating Ip parameter is passed in VNFD

### ISSUE THREAD

**Issue by DasSnehashish** [openbaton/NFVO#42]
While instantiating vnf , the VM instance created  is not having floating ip. In VNFD we are passing "floatingIp" parameter in connection_point descriptor as below
{
              "connection_point": [
                {
		  "floatingIp":"random",
                  "virtual_link_reference": "sawridgeInternal"
                }
              ]
 }

But the instantiated VM is not having a floating Ip and hence not reachable from external world. We are using openstack VIM.

Underlying Openstack vim is having enough floating IPs. We could manually attach the floating ip in openstack dashboard to VM instance.
But when we instantiate VNF through NFVO, the NFVO log below shows that NFVO is not able to attach floating IP to VM instance (even though in underlying openstack VIM floating Ips are available)

NFVO log:
---------------------------------------------------------------------------------------------------------------------------------
2016-12-01 10:44:13.570  INFO 5079 --- [cTaskExecutor-3] o.o.nfvo.core.core.ResourceManagement    : Launched VM with id: d59a2124-be81-443e-b8f7-ff99f0506587
2016-12-01 10:44:13.570  INFO 5079 --- [cTaskExecutor-3] o.o.nfvo.core.core.ResourceManagement    : NFVO wasn't able to all associate FloatingIPs. Is there enough available?
2016-12-01 10:44:13.570  INFO 5079 --- [cTaskExecutor-3] o.o.nfvo.core.core.ResourceManagement    : Expected FloatingIPs: {sawridgeInternal=random}
2016-12-01 10:44:13.570  INFO 5079 --- [cTaskExecutor-3] o.o.nfvo.core.core.ResourceManagement    : Real FloatingIPs: []
---------------------------------------------------------------------------------------------------------------------------------
If anyone has faced this kind of issue, please let us know the solution

**Comment by gc4rella** [comment]
Please provide the full log of the OpenStack plugin and check that the private network you are using is attached via the router to the external network.

**Comment by DasSnehashish** [comment]
yes,it is attached to a router to the external network , 
and we are manually able to assign a floating ip to the newly create VM and i also ping to that VM from outside world.
please check the attach plugnlog file 
[plugnLog.DOCX](https://github.com/openbaton/NFVO/files/636642/plugnLog.DOCX)

**Comment by gc4rella** [comment]
the file you sent is corrupted. Please send files via gist from now on: https://gist.github.com/

I also replied you via email. I think your floating IP pool does not have free IPs.

**Comment by DasSnehashish** [comment]
thanks Giuseppe,This issue is resolved ..
i communicated about this by mail ...thanks for your cooperation .
