### ISSUE TITLE
ems pgp error with key EF11C639332995F2

### ISSUE THREAD

**Issue by jolly2** [openbaton/NFVO#43]
Env: latest openbaton release with openstack.
A few days ago , VNFs launched by OpenBaton used to work perfectly fine. Now, when i try to launch new ones , ems does not get installed in the VM instance. apt-get update is failing with GPG error public key not found EF11C639332995F2. Tried manually receiving the key , but, says key not found.
Also, looked for this key on http://keyserver.ubuntu.com/. It says key not found. Has the key changed?
Thanks!

**Comment by gc4rella** [comment]
No, the key was not changed. We also tested it and it did not give any issues. Please check it again, maybe was a temporary issue on your side.
