### ISSUE TITLE
ems does not clone scripts file from github

### ISSUE THREAD

**Issue by chart2023** [openbaton/NFVO#44]
Dear sir,
I use NFVO version 3.0 and 3.01. I found the problem that ems does not clone script files from github.
Please give me a suggestion to fix this problem.
ems version 0.19
log file from /var/log/openbaton/ems-receiver.log as below.
> ubuntu@nscl6-255:/opt/openbaton$ ll -lt
total 12
drwxr-xr-x 3 7598 2600 4096 Dec  9 14:12 ./
drwxr-xr-x 2 7598 2600 4096 Dec  9 00:37 ems/
drwxr-xr-x 3 root root 4096 Dec  9 00:34 ../
ubuntu@nscl6-255:/opt/openbaton$ cat /var/log/openbaton/ems-receiver.log
INFO:__main__:EMS configuration paramters are hostname: newName1, username: guest, password: *****, autodel: true, heartbeat: 60, exchange name: openbaton-exchange
INFO:pika.adapters.base_connection:Connecting to 127.0.0.1:5672
WARNING:pika.adapters.base_connection:Connection to 127.0.0.1:5672 failed: [Errno 111] Connection refused
WARNING:pika.connection:Could not connect, 0 attempts left
INFO:__main__:EMS configuration paramters are hostname: newName1, username: guest, password: *****, autodel: true, heartbeat: 60, exchange name: openbaton-exchange
INFO:pika.adapters.base_connection:Connecting to 127.0.0.1:5672
WARNING:pika.adapters.base_connection:Connection to 127.0.0.1:5672 failed: [Errno 111] Connection refused
WARNING:pika.connection:Could not connect, 0 attempts left
INFO:__main__:EMS configuration paramters are hostname: nscl6-255, username: admin, password: *****, autodel: true, heartbeat: 900, exchange name: openbaton-exchange
INFO:pika.adapters.base_connection:Connecting to 192.168.9.16:5672
INFO:pika.adapters.blocking_connection:Created channel=1
INFO:receiver:Received message:
INFO:receiver:{"action":"CLONE_SCRIPTS","payload":"https://github.com/chart2023/NIP2.git","script-path":"/opt/openbaton/scripts"}
INFO:receiver:Cloning from: https://github.com/chart2023/NIP2.git into /opt/openbaton/scripts
INFO:receiver:answer is: {"status": 0, "output": "[u'README.md', u'add-iplbaas.sh', u'setup-shard.sh', u'install-nip.sh', u'setup-mongodb.sh', u'install-nscl.sh', u'start-nscl.sh', u'server_configure.sh', u'db_info.sh', u'client_configure.sh', u'request-vip-lbaas.sh', u'test.sh', u'exchangekey.exp', u'get-iplbaas.sh', u'register-lbaas.sh', u'.git', u'register-shard.sh', u'start-nip.sh', u'initshard.js', u'init-mongo.sh']", "err": ""}
INFO:__main__:Answer sent
INFO:receiver:Received message:
INFO:receiver:{"action":"EXECUTE","payload":"install-nscl.sh","env":{"private_floatingIp":"192.168.9.114","hostname":"nscl6-255","private":"10.0.14.4"}}
INFO:receiver:Received execute command
INFO:receiver:Executing: /opt/openbaton/scripts/install-nscl.sh with env {u'private_floatingIp': u'192.168.9.114', u'hostname': u'nscl6-255', u'private': u'10.0.14.4'}
INFO:receiver:Executed: ERR:  OUT:
INFO:receiver:answer is: {"status": 0, "output": "", "err": ""}
INFO:__main__:Answer sent

**Comment by lorenzotomasini** [comment]
Hi,

From the log you sent, not only the scripts are cloned

```
INFO:receiver:Received message: INFO:receiver:{"action":"CLONE_SCRIPTS","payload":"https://github.com/chart2023/NIP2.git","script-path":"/opt/openbaton/scripts"} INFO:receiver:Cloning from: https://github.com/chart2023/NIP2.git into /opt/openbaton/scripts INFO:receiver:answer is: {"status": 0, "output": "[u'README.md', u'add-iplbaas.sh', u'setup-shard.sh', u'install-nip.sh', u'setup-mongodb.sh', u'install-nscl.sh', u'start-nscl.sh', u'server_configure.sh', u'db_info.sh', u'client_configure.sh', u'request-vip-lbaas.sh', u'test.sh', u'exchangekey.exp', u'get-iplbaas.sh', u'register-lbaas.sh', u'.git', u'register-shard.sh', u'start-nip.sh', u'initshard.js', u'init-mongo.sh']", "err": ""} 
```

But also the first script is also executed. I believe you are facing  a different issue. Could you provide us the log of nfvo and of generic?

Lorenzo

**Comment by chart2023** [comment]
[genericvnfm.txt](https://github.com/openbaton/NFVO/files/642071/genericvnfm.txt)
Dear sir, Please see generic vnfm log in the attachment. However, my OpenBaton is failed now then I will re-install it asap.

**Comment by gc4rella** [comment]
hi @chart2023, please double check that the /opt/openbaton/scripts has content in the VM. I also think that the problem is mainly on the script execution and not on the clone operation

**Comment by chart2023** [comment]
Sorry everybody, It's my fault. The problem cause from my script file.

**Comment by gc4rella** [comment]
ok
