### ISSUE TITLE
functionality for resetting the password

### ISSUE THREAD

**Issue by gc4rella** [openbaton/NFVO#55]
admin should be able to reset users passwords. 
also users should be able to reset their passwords in case it is forgotten.

**Comment by mpauls** [comment]
Done for admins. Admins can reset passwords for other users with the following call:
PUT /api/v1/users/changepwd/{username} body: {"new_pwd":"newPassword"}

**Comment by gc4rella** [comment]
@ogozman what's the status here?

**Comment by ogozman** [comment]
@gc4rella Admin can reset password for the user(in dashboard admin user management tab). This issue is still opened because no decision was reached regarding resetting the admin password, as in how exactly this must be implemented

**Comment by mpauls** [comment]
kept open for the second point of giving the users the option to reset their passwords themself
