### ISSUE TITLE
Updating multiple VNF Packages may generate multiple image uploads

### ISSUE THREAD

**Issue by gc4rella** [openbaton/NFVO#84]
When you upload multiple packages, which all may refer to the same image, the NFVO will trigger multiple image uploads, although a single image upload may be sufficient.

**Comment by lorenzotomasini** [comment]
should the VNFPackage onboard be sequential then?

**Comment by gc4rella** [comment]
I think the first VNF Package upload should trigger the image upload process, and the following should verify whether the image already exists (meaning is being downloaded) or not. I think the image state introduced by @mpauls could be useful for this scenario.

**Comment by lorenzotomasini** [comment]
The image status was done by @radoslavvlaskovski and i think he told me that this issue was fixed, better a confirmation from him before closing

**Comment by radoslavvlaskovski** [comment]
The image-status branch contains the changes, but the fix required also changes on the model, but I think the image-status branch on openbaton-libs is still not merged.

**Comment by lorenzotomasini** [comment]
@zohaibhassan122 I need to know where are the changes in the dashboard for this. i must be included in rel4

**Comment by zohaibhassan122** [comment]
@lorenzotomasini I have these changes in my local version in my computer, I asked @radoslavvlaskovski  even two days ago, because first he has to push changes and then I should push my changes to develop branch, I can come tomorrow for short time at  15:00 and push the changes to develop. Just send me a message on slack.
