### ISSUE TITLE
Memory Leak RabbitMQ Connection

### ISSUE THREAD

**Issue by Rizwan-Qamar** [openbaton/NFVO#98]
Any call to openstack plugin opens a new connection in RabbitMQ and it is not closed. (@PreDestroy annotated method is not invoked for prototype beans)

1. Method **executeRPC** in **PluginCaller** class makes the request to plugin and closes the channel but not the connection. Closing the connection here will break **getLeftQuota** method in **VimBroker** class. (As it is using same Vim instance two times after first request connection is closed.)
```
      try {
        channel.close();        
      } catch (TimeoutException e) {
        e.printStackTrace();
      }
```
2. When returnType==null **executeRPC** neither closes channel nor connection.

```
 try {
        channel.queueDelete(replyQueueName);
      } catch (Exception ignored) {
      }
```

**Comment by lorenzotomasini** [comment]
this fix should be closed by [this](https://github.com/openbaton/openbaton-libs/pull/23) pull request
